// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type ProfileImages struct {
	ID         int64
	UserID     int64
	FilePath   string
	UploadedAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
