// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Addresses struct {
	ID         int64
	UserID     int64
	ZipCode    string
	Prefecture string
	City       string
	Street     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ProfileImages struct {
	ID         int64
	UserID     int64
	FilePath   string
	UploadedAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Profiles struct {
	ID             int64
	UserID         int64
	FirstName      string
	LastName       string
	FirstNameRoman string
	LastNameRoman  string
	Birthdate      time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Users struct {
	ID          int64
	Auth0UserID string
	Email       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
