
-- +migrate Up
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  auth0_user_id VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) UNIQUE DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_auth0_user_id (auth0_user_id),
  INDEX idx_email (email)
);

-- +migrate Down
DROP TABLE IF EXISTS users;
